language: php

php:
  - 5.3.2

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - wget http://getcomposer.org/composer.phar
  #- cp -ap Tests/composer.json.dist ./composer.json
  - php composer.phar install ./Tests/composer.json.dist

notifications:
  email:
    - gdeveloperaccount@gmail.com