language: php

php:
  - 5.3.2

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - wget http://getcomposer.org/composer.phar
  - cp Tests/composer.json.dist ./composer.json
  - php composer.phar install
  - ls

notifications:
  email:
    - gdeveloperaccount@gmail.com