language: php

php:
  - 5.3.2

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - pyrus install phpunit/DbUnit
  - mkdir -p app/cache app/logs
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit
#  - php app/console doctrine:database:create

script: "phpunit -c app"

notifications:
  email:
    on_failure: always
    on_success: change